f() -/>
  x = try: <- g() catch err: err
